---
resolv::options:
  - "timeout:1"
  - "attempts:1"
  - "rotate"
  - "single-request"
  - "single-request-reopen"
resolv::resolvers:
  - "10.2.0.254"
  - "10.2.3.254"
resolv::search:
  - "swcnet.net"
  - "wlan.swcnet.net"
  - "mgmt.swcnet.net"
