---
classes:
  - "transmission"
  - "sabnzb"
  - "sickbeard"
  - "unrar"

apt::repos:
  "jcfp":
    enabled: true
    location: "http://ppa.launchpad.net/jcfp/ppa/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "main"
    include_src: false
    key: "0x98703123E0F52B2BE16D586EF13930B14BB9F05F"
    key_server: "hkp://keyserver.ubuntu.com:11371"


transmission:
  download_dir: "/data/torrents"
  rpc-whitelist-enabled: false
  config_dir: "/var/lib/transmission-daemon/info"

sabnzb::config::run_as_user: "sabnzb"
sabnzb::config::https_port: 9090
