---
classes:
  - "samba"
  - "unrar"
  - "owncloud"

samba::config::workgroup: "SWC"
samba::config::server_string: "%{::hostname}"
samba::config::shares:
  store:
    comment: "Movies, Music, Etc.."
    path: "/data"
    guest_ok: "no"
    browseable: "yes"
    create_mask: "0664"
    directory_mask: "0775"
    writeable: "yes"
  usb:
    comment: "USB Mount"
    path: "/usb"
    guest_ok: "no"
    browseable: "yes"
    create_mask: "0664"
    directory_mask: "0775"
    writeable: "yes"

apt::repos:
  "multiverse":
    enabled: true
    location: "http://archive.ubuntu.com/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "multiverse"
    include_src: false
  "ownCloud":
    enabled: true
    location: "http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_13.10/"
    release: ""
    repos: "/"
    key: "BA684223"
    key_source: "http://download.opensuse.org/repositories/isv:/ownCloud:/community/xUbuntu_13.10/Release.key"
    include_src: false
