---
classes:
  - "samba"

samba::config::workgroup: "SWC"
samba::config::server_string: "%{::hostname}"
samba::config::shares:
  store:
    comment: "Movies, Music, Etc.."
    path: "/data"
    guest_ok: "no"
    browseable: "yes"
    create_mask: "0664"
    directory_mask: "0775"
