---
classes:
  - "apache2"
  - "mysql::server"
  - "php5"
  - "php5::mysql"
  - "observium"

apt::repos:
  "webupd8team":
    enabled: true
    location: "http://ppa.launchpad.net/webupd8team/java/ubuntu"
    release: "%{::lsbdistcodename}"
    repos: "main"
    include_src: false
    key: "EEA14886"
    key_server: "keyserver.ubuntu.com"

observium::database_name: "observium"
observium::database_user: "observium"
observium::database_pass: "observium"
observium::database_server: "localhost"
