---
classes:
  - 'apt::unattended'
  - "zram"
  - "hosts"
  - "proxmox"
  - "proxmox::scripts"
  - "csf::post"

motd::note: pve

apt::repos:
  "pve-enterprise":
    enabled: false
    location: "https://enterprise.proxmox.com/debian"
    release: "stable"
    repos: "main"
    include_src: false
  "pve-no-subscription":
    enabled: true
    location: "http://download.proxmox.com/debian"
    release: "wheezy"
    repos: "pve-no-subscription"
    include_src: false

kernel::modules:
  nfs:
    ensure: "present"
